# Generated by Django 3.2.1 on 2021-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=12),
        ),
    ]
