# Generated by Django 3.2.1 on 2021-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='flag',
            field=models.CharField(default='', max_length=2),
        ),
    ]
